import { useState } from 'react';
import Link from 'next/link';
import { motion } from 'framer-motion';

import { NavMenu } from 'components/NavMenu';
import Head from 'next/head';

function Home() {
	const [loading, setLoading] = useState(false);
	const container = {
		hidden: { opacity: 0 },
		show: {
			opacity: 1,
			transition: {
				duration: 1,
				staggerChildren: 0.5,
			},
		},
	};

	const item = {
		hidden: { opacity: 0, y: -10 },
		show: { opacity: 1, y: 10 },
	};

	return (
		<div>
			<Head>
				<title>TrackDuels</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='https://fav.farm/⚔️' />
			</Head>
			<div className='space-y-8 px-4 py-4 sm:py-8'>
				<NavMenu />
				<motion.div
					variants={container}
					initial='hidden'
					animate='show'
					className='fixed inset-0 mx-auto flex h-screen max-w-2xl flex-col justify-center'>
					<div className='space-y-8 self-center px-4'>
						<div className='space-y-2'>
							<motion.h1
								variants={item}
								className='max-w-2xl font-serif text-2xl leading-normal sm:text-3xl'>
								What is the best song on my playlist ?
							</motion.h1>
							<motion.p
								variants={item}
								className='max-w-lg text-sm text-gray-500 dark:text-zinc-500 sm:text-base'>
								The app will present you with 2 random songs pulled from my{' '}
								<a
									target='_blank'
									rel='noopener noreferrer'
									className='text-indigo-500 underline underline-offset-2 dark:text-indigo-500'
									href='https://open.spotify.com/playlist/6rnNiTWsUxMFUFe2q8JOkp?si=79203836ee6a41e5'>
									playlist
								</a>{' '}
								and you can vote for your favorite out of the 2 by double
								clicking on it.
							</motion.p>
							<motion.p
								variants={item}
								className='max-w-lg text-sm text-gray-500 dark:text-zinc-500 sm:text-base'>
								You can see what songs people like the most by checking out the
								Leaderboard page.
							</motion.p>
						</div>
						<div className='flex items-center space-x-2'>
							<motion.div variants={item}>
								<Link
									onClick={() => setLoading(true)}
									className='inline-block rounded-md bg-indigo-500 px-2 py-2 text-sm text-white transition duration-300 hover:bg-indigo-600 sm:px-4 sm:py-2 sm:text-base'
									href='/vote'>
									{loading ? (
										<svg
											className='h-6 w-6 animate-spin'
											xmlns='http://www.w3.org/2000/svg'
											viewBox='0 0 24 24'>
											<path fill='none' d='M0 0h24v24H0z' />
											<path d='M18.364 5.636L16.95 7.05A7 7 0 1 0 19 12h2a9 9 0 1 1-2.636-6.364z' />
										</svg>
									) : (
										'Get Started'
									)}
								</Link>
							</motion.div>
							<motion.div variants={item}>
								<Link
									onClick={() => setLoading(true)}
									className='inline-block rounded-md bg-indigo-100 px-2 py-2 text-sm text-indigo-600 transition duration-300 hover:bg-indigo-200 dark:bg-indigo-900 dark:text-indigo-100 dark:hover:bg-indigo-800 sm:px-4 sm:py-2 sm:text-base'
									href='/leaderboard'>
									{loading ? (
										<svg
											className='h-6 w-6 animate-spin'
											xmlns='http://www.w3.org/2000/svg'
											viewBox='0 0 24 24'>
											<path fill='none' d='M0 0h24v24H0z' />
											<path d='M18.364 5.636L16.95 7.05A7 7 0 1 0 19 12h2a9 9 0 1 1-2.636-6.364z' />
										</svg>
									) : (
										'Leaderboard'
									)}
								</Link>
							</motion.div>
						</div>
					</div>
				</motion.div>
			</div>
		</div>
	);
}

export default Home;
